labels:
  - name: "버그"
    color: "d73a4a"
    description: "버그 리포트"
    oldname:
      - "bug"

  - name: "기능개선"
    color: "a2eeef"
    description: "기능 추가/개선 제안"
    oldname:
      - "enhancement"

  - name: "문서"
    color: "0075ca"
    description: "문서 관련 작업"
    oldname:
      - "documentation"

  - name: "질문"
    color: "d876e3"
    description: "질문/문의"
    oldname:
      - "question"

  - name: "해결하지 않음"
    color: "ffffff"
    description: "해결 계획 없음"
    oldname:
      - "wontfix"

  - name: "무효"
    color: "e4e669"
    description: "재현 불가/요건 불충족"
    oldname:
      - "invalid"

  - name: "중복"
    color: "cfd3d7"
    description: "중복 이슈"
    oldname:
      - "duplicate"

  - name: "첫 이슈"
    color: "7057ff"
    description: "처음 기여자에게 적합"
    oldname:
      - "good first issue"

  - name: "도움 환영"
    color: "008672"
    description: "도움이 필요한 항목"
    oldname:
      - "help wanted"
