services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boardhole
      MYSQL_USER: boardhole
      MYSQL_PASSWORD: boardhole123
    volumes:
      - mysql_dev_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - dev-network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 10
    networks:
      - dev-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/boardhole?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: boardhole
      SPRING_DATASOURCE_PASSWORD: boardhole123
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      BOARDHOLE_CORS_ALLOWED_ORIGINS: http://localhost:8080,http://127.0.0.1:8080,http://localhost:3000
      BOARDHOLE_DEFAULT_USERS_ADMIN_PASSWORD: Admin123!
      BOARDHOLE_DEFAULT_USERS_REGULAR_PASSWORD: User123!
    volumes:
      - ./src:/app/src:ro  # Mount source for hot reload observation (read-only)
      - app_dev_logs:/app/logs
    networks:
      - dev-network

volumes:
  mysql_dev_data:
  redis_dev_data:
  app_dev_logs:

networks:
  dev-network:
    driver: bridge