services:
  mysql:
    image: mysql:9.4
    container_name: boardhole-mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boardhole
      MYSQL_USER: boardhole
      MYSQL_PASSWORD: boardhole123
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
  
  redis:
    image: redis:8-alpine
    container_name: boardhole-redis
    ports:
      - "16379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis-data:
  mysql-data:
