services:
  postgres:
    image: postgres:17-alpine
    container_name: boardhole-postgres
    ports:
      - "5432"
    environment:
      POSTGRES_USER: boardhole
      POSTGRES_PASSWORD: boardhole123
      POSTGRES_DB: boardhole
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U boardhole -d boardhole" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  redis:
    image: redis:7-alpine
    container_name: boardhole-redis
    ports:
      - "6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  redis-data:
  postgres-data:
