# 개발 환경 설정
# Database (Docker Compose 연동)
spring.docker.compose.enabled=true
# JPA/Hibernate Properties (개발 환경)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Logging (개발 환경)
# ANSI 컬러 강제(콘솔 컬러 출력)
spring.output.ansi.enabled=ALWAYS
logging.pattern.level=%5p [trace:%X{traceId}]
logging.level.bunny.boardhole=DEBUG
logging.level.org.springframework.security=DEBUG
# Board Hole 기본 사용자 설정 (개발 환경)
boardhole.default-users.admin.password=admin123
boardhole.default-users.regular.password=user123
# Manual Database Configuration (Docker Compose 비활성화 시 사용)
# spring.datasource.url=jdbc:mysql://localhost:13306/boardhole?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.username=boardhole
# spring.datasource.password=boardhole123

# Database 연결 UTF-8 설정 (Docker Compose용)
spring.datasource.url=jdbc:mysql://localhost:13306/boardhole?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
