# ========================================
# SMTP 프로파일 전용 설정
# 실제 이메일 발송을 위한 SMTP 설정
# ========================================

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    # username과 password를 오버라이드 해야합니다 (SMTP 사용시 필수)
    # username: your-email@gmail.com
    # password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    test-connection: false

# SMTP 사용시 이메일 관련 설정
boardhole:
  email:
  # Outbox 패턴 활성화 (실제 발송시 필요) - 현재 미사용
  # outbox:
  #   enabled: true