spring:
  application:
    name: board-hole
  messages:
    basename: messages,ValidationMessages
    
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    active: dev

boardhole:
  default-users:
    admin:
      username: admin
      name: 관리자
      email: admin@boardhole.com
      password: admin123
    regular:
      username: user
      name: 일반 사용자
      email: user@boardhole.com
      password: user123
  cors:
    allowed-origins: "http://localhost:8080,http://127.0.0.1:8080,http://localhost:3000"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600
