# ========================================
# 운영 환경 전용 설정
# 보안 강화 및 환경변수 기반 설정
# ========================================

spring:
  # 운영 데이터베이스 설정 (환경변수 필수)
  datasource:
    url:   # 필수 환경변수
    username:   # 필수 환경변수
    password:   # 필수 환경변수
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 만 지원 강제

  # JPA 운영 설정
  jpa:
    hibernate:
      ddl-auto: validate  # 운영에서는 스키마 검증만

  # Redis 운영 설정 (환경에 맞게 설정 필요)
  data:
    redis:
      host:  # Redis 호스트 설정 필요
      port:  # Redis 포트 설정 필요
      # password:  # 필요시 Redis 비밀번호 설정

# 운영 서버 보안 설정
server:
  servlet:
    session:
      cookie:
        secure: true      # HTTPS 전용
        http-only: true   # JavaScript 접근 차단
        same-site: strict # CSRF 공격 방지

# 운영 로깅 설정 - 루트 프로파일에서 상속, 파일 로깅 추가
logging:
  pattern:
    # 파일용 패턴 (컬러 없음)
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %-40.40logger{39} : %m%n%wEx"
  
  # 파일 로깅 설정
  file:
    name: /var/log/boardhole/application.log

# 운영 환경 애플리케이션 설정
boardhole:
  # 운영 CORS 설정
  cors:
    # allowed-origins를 오버라이드 해야합니다
    allowed-origins: "https://need.change" # 허용할 도메인
  # 운영 사용자 설정
  default-users:
    admin:
      password: "need-change" # 필수 환경변수
    regular:
      password: "need-change" # 필수 환경변수
