# ========================================
# Board-Hole 애플리케이션 공통 설정
# 모든 환경에서 공유되는 기본 설정
# ========================================

spring:
  # 애플리케이션 기본 정보
  application:
    name: board-hole
  
  # 메시지 소스 설정
  messages:
    basename: messages,ValidationMessages
    encoding: UTF-8

  # MVC 설정
  mvc:
    problemdetails:
      enabled: true  # Enable RFC 7807 Problem Details for HTTP APIs
  
  # JPA 공통 설정
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  # 기본 프로필 (로컬 개발시 dev 사용)
  profiles:
    active: dev
  
  # ANSI 컬러 출력 설정
  output:
    ansi:
      enabled: DETECT  # 터미널 지원시 자동 활성화 (ALWAYS, DETECT, NEVER)
  
  session:
    redis:
      namespace: board-hole:session
      flush-mode: on-save
    timeout: 30m
  
  # 비동기 처리 설정 - Spring Boot 기본 제공
  task:
    execution:
      pool:
        core-size: ${ASYNC_CORE_SIZE:2}
        max-size: ${ASYNC_MAX_SIZE:10}
        queue-capacity: ${ASYNC_QUEUE_CAPACITY:100}
        keep-alive: 60s
      thread-name-prefix: Async-
      shutdown:
        await-termination: true
        await-termination-period: 10s
  
  # 이메일 설정
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${MAIL_HOST:smtp.gmail.com}
    test-connection: false

# ========================================
# 애플리케이션 도메인 설정
# ========================================
boardhole:
  # 검증 규칙
  validation:
    board:
      title-max-length: 200
      content-max-length: 10000
    user:
      username-min-length: 3
      username-max-length: 20
      password-min-length: 8
      password-max-length: 100
      email-max-length: 255
      name-min-length: 1
      name-max-length: 50
    email-verification:
      expiration-minutes: 30
      code-length: 6
      signup-expiration-hours: 24
  
  # 보안 설정
  security:
    verification-code:
      length: 6
      expiry-minutes: 30
      charset: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    role-prefix: "ROLE_"
    session-timeout-minutes: 30
  
  # 인증 설정
  auth:
    default-role: "USER"

  # 성능 임계값
  performance:
    logging:
      fast-threshold-ms: 100
      normal-threshold-ms: 500
      slow-threshold-ms: 1000
      duration-threshold-ms: 1000
  
  # 이메일 관련 설정
  email:
    base-url: ${EMAIL_BASE_URL:http://localhost:8080}
    from-name: ${EMAIL_FROM_NAME:Board-Hole}
    verification-expiration-hours: 24
    rate-limit:
      per-hour: 5
      per-day: 20
  
  # CORS 기본값 (환경별 프로필에서 오버라이드 권장)
  cors:
    path-patterns: "/api/**"
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "Origin,Content-Type,Accept,Authorization,X-Requested-With"
    exposed-headers: ""
    allow-credentials: false
    max-age: 3600
  
  # Problem Details API 설정
  problem:
    # 문제 유형(type) 링크의 베이스 URI
    # 비워두면 urn:problem-type:{slug} 형식으로 자동 생성
    base-uri: # null (의도적으로 비움)
  
  # 기본 사용자 템플릿 (비밀번호는 환경별 프로필에서 설정)
  default-users:
    admin:
      username: admin
      name: 관리자
      email: admin@boardhole.com
    regular:
      username: user
      name: 일반 사용자
      email: user@boardhole.com
  
  # OpenAPI 문서 설정
  api:
    title: Board-Hole API
    version: 0.0.1-SNAPSHOT
    description: Board-Hole REST API Documentation
    terms-of-service: https://boardhole.com/terms
    contact:
      name: BUNNY
      email: bunny@xiyo.dev
      url: mailto:contact@xiyo.dev
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0

# ========================================
# 로깅 공통 설정
# ========================================
logging:
  pattern:
    # 컬러풀한 콘솔 출력 패턴
    console: "%clr(%d{HH:mm:ss.SSS}){cyan} %clr(%-5level) %clr([%15.15t]){magenta} %clr(%-40.40logger{39}){yellow} %clr(:){faint} %m%n%wEx"
    # 파일용 패턴 (컬러 없음)
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %-40.40logger{39} : %m%n%wEx"

# ========================================
# 서버 공통 설정
# ========================================
# 서버 관련 공통 설정은 환경별로 다르게 적용됨
# 필요시 여기에 공통 설정 추가 

# ========================================
# OpenAPI / Swagger UI 설정 (공통)
# ========================================
springdoc:
  # 스캔 범위 제한 (필요한 API만 포함)
  paths-to-match:
    - /api/**
