spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/boardhole?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul}
    username: ${DATABASE_USERNAME:boardhole}
    password: ${DATABASE_PASSWORD:boardhole123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  docker:
    compose:
      enabled: false

boardhole:
  default-users:
    admin:
      password: ${BOARDHOLE_ADMIN_PASSWORD:ChangeMe!123}
    regular:
      password: ${BOARDHOLE_USER_PASSWORD:ChangeMe!456}

server:
  servlet:
    session:
      timeout: 30m
      cookie:
        secure: true
        http-only: true
        same-site: strict
