# ========================================
# Board-Hole 애플리케이션 공통 설정
# 모든 환경에서 공유되는 기본 설정
# ========================================

spring:
  # 애플리케이션 기본 정보
  application:
    name: board-hole
  
  # 기본 프로필 설정
  profiles:
    active: dev, openapi

# ========================================
# 로깅 공통 설정
# ========================================
logging:
  pattern:
    # 컬러풀한 콘솔 출력 패턴
    console: "%clr(%d{HH:mm:ss.SSS}){cyan} %clr(%-5level) %clr([%15.15t]){magenta} %clr(%-40.40logger{39}){yellow} %clr(:){faint} %m%n%wEx"

# ========================================
# 애플리케이션 도메인 설정
# ========================================
boardhole:
  # 보안 설정
  security:
    verification-code:
      length: 6
      expiry-minutes: 30
      charset: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    role-prefix: "ROLE_"
    session-timeout-minutes: 30
  
  # 인증 설정
  auth:
    default-role: "USER"

  # 성능 임계값
  performance:
    logging:
      fast-threshold-ms: 100
      normal-threshold-ms: 500
      slow-threshold-ms: 1000
      duration-threshold-ms: 1000
  
  # 유효성 검증 설정
  validation:
    email-verification:
      expiration-ms: 7200000              # 이메일 인증 만료시간 (2시간)
  
  # 이메일 관련 설정
  email:
    base-url: http://localhost:8080
    from-name: Board-Hole
    rate-limit:
      per-hour: 5
      per-day: 20
    # Outbox 재시도 설정
    outbox:
      enabled: true
      max-retry-count: 5                  # 총 5회 재시도 (최초 1회 + 4회 재시도)
      scheduler-rate: 600000              # 10분마다 실행 (600,000ms = 10분)
      retention-days: 30
      cleanup-cron: "0 0 2 * * *"        # 매일 새벽 2시
      stats-cron: "0 0 * * * *"          # 매시간
  
  # CORS 기본값 (환경별 프로필에서 오버라이드 권장)
  cors:
    path-patterns: "/api/**"
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "Origin,Content-Type,Accept,Authorization,X-Requested-With"
    exposed-headers: # 의도적으로 비움
    allow-credentials: true
    max-age: 3600
  
  # Problem Details API 설정
  problem:
    # 문제 유형(type) 링크의 베이스 URI
    # 비워두면 urn:problem-type:{slug} 형식으로 자동 생성
    base-uri: # null (의도적으로 비움)
  
  # 기본 사용자 템플릿 (비밀번호는 환경별 프로필에서 설정)
  default-users:
    admin:
      username: admin
      password: Admin123!  # 환경별로 오버라이드 권장 (정책 준수: 대/소문자+숫자+특수문자)
      name: 관리자
      email: admin@boardhole.com
    regular:
      username: user
      password: User123!  # 환경별로 오버라이드 권장 (정책 준수)
      name: 일반 사용자
      email: user@boardhole.com
