# 스프링 애플리케이션 이름 설정
spring.application.name=board-hole
# 기본 프로파일을 dev로 설정
spring.profiles.active=dev
# JPA/Hibernate Properties (공통)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
# SpringDoc OpenAPI (공통)
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
# Board Hole 기본 사용자 설정 (공통)
boardhole.default-users.admin.username=admin
boardhole.default-users.admin.name=관리자
boardhole.default-users.admin.email=admin@boardhole.com
boardhole.default-users.regular.username=user
boardhole.default-users.regular.name=일반 사용자
boardhole.default-users.regular.email=user@boardhole.com
# CORS 설정 (커스텀 프로퍼티)
boardhole.cors.allowed-origins=http://localhost:8080,http://127.0.0.1:8080,http://localhost:3000
boardhole.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
boardhole.cors.allowed-headers=*
boardhole.cors.allow-credentials=true
boardhole.cors.max-age=3600

# 로깅 설정 - 색상 및 한글 지원
spring.output.ansi.enabled=always
logging.charset.console=UTF-8
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint} %clr([%thread]){magenta} %clr(%-5level){highlight} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n

# 커스텀 로깅 임계값 설정
boardhole.logging.performance.fast-threshold=100
boardhole.logging.performance.normal-threshold=500

# 다국어 설정
spring.messages.basename=messages,ValidationMessages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true
spring.messages.cache-duration=PT5M

# Redirect security (default: allow any origin; restrict in prod via env var or prod profile)
boardhole.redirect.allowed-origin=
spring.mvc.hiddenmethod.filter.enabled=true

# Jackson JSON 인코딩 설정 (JSON 응답 한글 깨짐 방지)
spring.jackson.serialization.write-char-arrays-as-json-arrays=true
spring.jackson.default-property-inclusion=NON_NULL
spring.jackson.serialization.indent-output=false
