spring:
  docker:
    compose:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 300
  datasource:
    url: jdbc:mysql://localhost:13306/boardhole?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.SQL_SLOW: INFO

boardhole:
  default-users:
    admin:
      password: admin123
    regular:
      password: user123
