# Spring Boot Application Configuration (YAML 형식)
spring:
  # 애플리케이션 기본 설정
  application:
    name: board-hole  # 스프링 애플리케이션 이름

  # 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:testdb  # H2 메모리 데이터베이스 URL (애플리케이션 종료시 데이터 삭제됨)
    driver-class-name: org.h2.Driver  # H2 데이터베이스 드라이버 클래스명
    username: sa  # 데이터베이스 접속 사용자명
    password:  # 데이터베이스 접속 비밀번호 (빈값)

  # H2 Console 설정 (개발용)
  h2:
    console:
      enabled: true  # H2 웹 콘솔 활성화 (http://localhost:8080/h2-console)

  # SQL 스크립트 실행 설정
  sql:
    init:
      mode: always  # 애플리케이션 시작시 항상 SQL 스크립트 실행
      schema-locations: classpath:schema.sql  # 실행할 스키마 SQL 파일 경로

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml  # MyBatis XML 매퍼 파일 위치 지정
  type-aliases-package: bunny.boardhole.domain  # 도메인 클래스 패키지 별칭 설정 (XML에서 풀패키지명 생략 가능)

# 로깅 설정 (선택사항)
logging:
  level:
    bunny.boardhole: DEBUG  # 애플리케이션 패키지의 로그 레벨을 DEBUG로 설정
    org.springframework.jdbc: DEBUG  # SQL 쿼리 로그 출력을 위한 설정