name: Master Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build (includes tests)
        run: ./gradlew clean build --no-daemon

      - name: Build bootJar
        run: ./gradlew bootJar --no-daemon

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: board-hole-jars
          path: build/libs/*.jar

      - name: Summary
        run: |
          echo "## ✅ Master Build Completed" >> $GITHUB_STEP_SUMMARY
          echo "- Branch: $GITHUB_REF_NAME" >> $GITHUB_STEP_SUMMARY
          echo "- Artifacts: build/libs/*.jar (uploaded)" >> $GITHUB_STEP_SUMMARY
