name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (ex: 1.6.0)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      discussions: write

    env:
      VERSION: ${{ github.event.inputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build & Test
        run: ./gradlew clean build

      - name: Run JReleaser
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew jreleaserFullRelease -PreleaseVersion=${VERSION}

      - name: Prepare release notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release view v${VERSION} --json body -q .body > RELEASE_NOTES.md

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push multi-arch image
        run: |
          SUMMARY=$(tr '\n' ' ' < RELEASE_NOTES.md | cut -c1-1800 | sed 's/"/\\"/g')
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f Dockerfile.cicd \
            -t ghcr.io/bunnyholes/boardhole:${VERSION} \
            -t ghcr.io/bunnyholes/boardhole:latest \
            --label org.opencontainers.image.version=${VERSION} \
            --label org.opencontainers.image.description="${SUMMARY}" \
            --push .

      - name: Upload release notes as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-notes-${{ env.VERSION }}
          path: RELEASE_NOTES.md
